runRoutingPreprocessor: true
runTidefilePreprocessor: true
runTidefilePreprocessorQA: false
runConfigFileQA: false
runRepackTidefile: false
tideFile: D:/QEDA/DWR/delta/DSM2-8.5.8be49770-win64_with_inputs/studies/historical/output/hist_fc_mss.h5 
routingPreprocessor:
  runInCondaEnv: true
  transProbsStartDate: 02jan2015
  transProbsEndDate: 30dec2015
  sampleTime_min: 15
  numCores: 8
tidefilePreprocessor:
  runInCondaEnv: true
  GZIPlevel: 9
  overwriteOrigTideFile: false
  overwriteNewTideFile: true
tidefilePreprocessorQA:
  runInCondaEnv: true
  origFile: /Users/djackson/Documents/QEDA/DWR/ECO_PTM_scenarios/v1.1.88.4_byYear_10apr24_orig/v1.1.88.4_2011.h5
  preprocessedFile: /Users/djackson/Documents/QEDA/DWR/ECO_PTM_scenarios/v1.1.88.4_byYear_10apr24_post_tidefilePreprocessor/v1.1.88.4_2011.h5
configFileQA:
  runInCondaEnv: true
  tideFile: D:/QEDA/DWR/delta/DSM2-8.5.8be49770-win64_with_inputs/studies/historical/output/hist_fc_mss.h5
  configFile: C:/Users/admin/Documents/QEDA/DWR/ECO_PTM_runs/testLeakage_14nov25/ptmConfig.yaml
repackTidefile:
  GZIPlevel: 9
